import sqlite3

db = sqlite3.connect('pity.db', check_same_thread = False)
sql = db.cursor()

sql.execute("""CREATE TABLE IF NOT EXISTS im_alone(phrase TEXT,id INT)""")
db.commit()
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('яя один', 0))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я один.', 1))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я один', 2))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я один?', 3))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('яя один?', 4))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я один??', 5))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я один..?', 6))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я один?..', 7))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я одна', 8))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я одна.', 9))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я одна?', 10))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я одна??', 11))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я одна..?', 12))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('я одна?..', 13))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('интересно один ли я', 14))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('интересно я один', 15))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('интересно я один?', 16))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('интересно я один??', 17))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('интересно я один?..', 18))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('интересно одна ли я', 19))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('интересно я одна', 20))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('интересно я одна?', 21))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('интересно я одна??', 22))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('интересно я одна?..', 23))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('/инфа я одна', 24))
sql.execute(f"INSERT INTO im_alone VALUES(?,?)", ('/инфа я один', 25))
db.commit()

sql.execute("""CREATE TABLE IF NOT EXISTS stickers(tg_id TEXT, id INT)""")
db.commit()
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgQAAxkBAAI4pGTB3K5fVGRx6-fd87OSbYXHpmhOAALBCwACSl-wUS7YsVA34l0hLwQ', 0))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgQAAxkBAAI4pmTB3LMhnGnPvfEI7dRu2O0Ky5oVAAIiHQACUX0AAVBvNmHdUFijpS8E', 1))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgQAAxkBAAI4qGTB3L-FRHMzc6H91IgOJVlbmKDlAALoCQACbQXpU3f0VcR0LKO4LwQ', 2))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgQAAxkBAAI4qmTB3MqqUkXh5DJ-9JOjsMmTPFLZAAJXDAAC9qA4UvIEg365VMTtLwQ', 3))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4rGTB3Nezqi4CybL0TYof81Ecd1-HAAJPHgACty44SFroRkiEtWuELwQ', 4))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4rmTB3NpQjPaylq-2eNw9SEkwG7KhAAKBGwAC6WBBSMRU1kCjzsQ2LwQ', 5))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4sGTB3PDvWcVP0nMMMc3Q3jZCTg8LAAL-FQACuKEoSKVpjcntejS8LwQ', 6))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4smTB3PFx2SZMQ3MbnIg8Yiq6F-zNAAKKEwACuFwpSH8mgDz9uZaELwQ', 7))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4tGTB3PnM1jNBaAYaLVdLJtOEjSdeAAItGgACO6ohSKWKglzs4mm-LwQ', 8))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4uGTB3RLluHvrSBQquqsuaWiDExhoAAKPGAACC6z4SwAByuVFguHK0i8E', 9))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4umTB3RmJ1RujXy1BdJXIQxB0xGX_AAKxFAACtFn5S2z5-pyuAoHGLwQ', 10))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4vGTB3SLtiDpaaYgfBCD6HTJdz6rlAAJeGQAC9NxoSASxw0lAvIJQLwQ', 11))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4vmTB3TJF6c5PTszPlNyCwUqn703LAAKEEwACOW7JS2ZVTlSwaykPLwQ', 12))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4wGTB3TRGoawqDHGvv6OY5jqvpBwUAALtEgACgCTIS7ELWSqTwy0YLwQ', 13))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4wmTB3UTLatuNIkF3HzHPko2vM3iEAALzFwACqkdJSC8ry4607EHCLwQ', 14))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4xmTCCVgYgj_vo3bYFZmWwxUCHQ_2AAJzMwACJXIRSoJM6cbVizIiLwQ', 15))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4yGTCCVpyxsw7K98YMOFpP4qA4d_RAAJ9NAACrb8QStpkLcCm9PDyLwQ', 16))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4ymTCCV1osUc1W6QX2OcpoDVn6R3NAAIEAAOEGRA_oqueBwRymoYvBA', 17))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4zGTCCXezXFSiN1UhjMFAdFY3IOqeAALTJwAC0QFJS6Lbwo1Vs0qsLwQ', 18))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4zmTCCXimGnqcK_LvZLZMHhO32koIAAJTKgACPSNJS-RST1h7Cb9CLwQ', 19))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgQAAxkBAAI40GTCCZoFiOu7UkOiy_37EN-KcZoBAALSAgACj7NZA06V6kbKvFjnLwQ', 20))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI40mTCCdBz7ZlJWRWWQYATlSMr9RrXAAJ7EwACYC4pSNF5jt3SitAMLwQ', 21))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI41GTCCeu4Arr2Wap-95RKw45_IHEiAAI_GgACwEZpSRPI-nLhMLoQLwQ', 22))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI41mTCCfRhT0p4OIr0XsQOfp01vcJUAAIqEwACoL74S74mGdF3Gg6ZLwQ', 23))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI42GTCCggbFHtSeI-tlgyVZ7aAPIoHAAK8DwACk1r5S2NA-mslGBz3LwQ', 24))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI42mTCCkWNkuVngQdB3K-7GV16YNG2AAJhAgAC81Y_FxQ-kB2ef5bKLwQ', 25))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI43GTCCk3TsC57mNkU54vakiSP69fuAAKGAgAC81Y_F7AEphqEvu5_LwQ', 26))
sql.execute(f"INSERT INTO stickers VALUES(?,?)", ('CAACAgIAAxkBAAI4xGTB3Uo0Mh-lrITWoOE2oBq6HX-YAAKMFAACGndJSHhnyYts9sZYLwQ', 27))
db.commit()

sql.execute("""CREATE TABLE IF NOT EXISTS whos_alone(phrase TEXT,id INT)""")
db.commit()
sql.execute(f"INSERT INTO whos_alone VALUES(?,?)", ('/кто один', 0))
sql.execute(f"INSERT INTO whos_alone VALUES(?,?)", ('/кто один?', 1))
sql.execute(f"INSERT INTO whos_alone VALUES(?,?)", ('кто один?', 2))
sql.execute(f"INSERT INTO whos_alone VALUES(?,?)", ('кто один??', 3))
sql.execute(f"INSERT INTO whos_alone VALUES(?,?)", ('кто один', 4))
sql.execute(f"INSERT INTO whos_alone VALUES(?,?)", ('кто один то', 5))
sql.execute(f"INSERT INTO whos_alone VALUES(?,?)", ('да кто один то', 6))
db.commit()

sql.execute("""CREATE TABLE IF NOT EXISTS replies(phrase TEXT,id INT)""")
db.commit()
sql.execute(f"INSERT INTO replies VALUES(?,?)", ('нет мы все вместе', 0))
sql.execute(f"INSERT INTO replies VALUES(?,?)", ('нет бро мы с тобой', 1))
sql.execute(f"INSERT INTO replies VALUES(?,?)", ('нет мы все тоже', 2))
sql.execute(f"INSERT INTO replies VALUES(?,?)", ('а как же мы(((', 3))
db.commit()